#!/usr/bin/env bash
# Personal Second Brain — interactive installer
# Asks the user for vault path, language, API key, cron expression, then:
#   - syncs Python deps via uv
#   - writes ~/.pm-second-brain/config.yaml
#   - initializes vault layout and sqlite-fts schema
#   - symlinks skill namespaces into ~/.opencode/skills and ~/.claude/skills
#   - renders MCP configs with concrete paths
#   - optionally installs a launchd daily-brief job (macOS)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/colors.sh
source "$HERE/lib/colors.sh"
# shellcheck source=lib/prompts.sh
source "$HERE/lib/prompts.sh"
# shellcheck source=lib/validate.sh
source "$HERE/lib/validate.sh"
# shellcheck source=lib/symlinks.sh
source "$HERE/lib/symlinks.sh"

say ""
info "Personal Second Brain — interactive setup"
say ""

# --- 1. Prerequisites -------------------------------------------------------
info "Checking prerequisites…"
MISSING=0
for c in bash python3 sqlite3 uv; do
  require_cmd "$c" || MISSING=1
done
if (( MISSING )); then
  fail "Install missing tools first. uv: https://github.com/astral-sh/uv"
  exit 1
fi
ok "prerequisites present"

# --- 2. Vault path ----------------------------------------------------------
say ""
info "Obsidian vault"
VAULT_ROOT=""
while true; do
  VAULT_ROOT=$(ask "Vault path (absolute, e.g. /Users/you/Documents/Obsidian/PM)" "$HOME/Documents/Obsidian/PM-SecondBrain")
  # Expand a leading ~ if user typed it.
  VAULT_ROOT="${VAULT_ROOT/#\~/$HOME}"
  if is_absolute_path "$VAULT_ROOT"; then break; fi
  warn "path must be absolute (start with /). Try again."
done

if [[ ! -d "$VAULT_ROOT" ]]; then
  if ask_yn "Directory $VAULT_ROOT does not exist. Create it?" y; then
    mkdir -p "$VAULT_ROOT"
    ok "created $VAULT_ROOT"
  else
    fail "cannot proceed without a vault directory"
    exit 1
  fi
fi

# --- 3. Language / API key / cron ------------------------------------------
say ""
OUT_LANG=$(ask "Output language [ru/en]" "ru")
case "$OUT_LANG" in ru|en) ;; *) warn "unknown lang '$OUT_LANG', defaulting to ru"; OUT_LANG="ru" ;; esac

say ""
CRON_TIME=$(ask "Daily brief cron (m h dom mon dow)" "0 8 * * 1-5")

# --- 4. Install Python deps -------------------------------------------------
# Anthropic API key is NOT requested here — OpenCode and Claude Code each
# carry their own provider auth. This skill-pack only invokes them as runtimes.
say ""
info "Syncing Python dependencies (uv sync)…"
( cd "$HERE" && uv sync --quiet ) || { fail "uv sync failed"; exit 1; }
ok "deps synced"

# --- 5. Write config.yaml ---------------------------------------------------
mkdir -p "$HOME/.pm-second-brain"
CONFIG_PATH="$HOME/.pm-second-brain/config.yaml"
cat > "$CONFIG_PATH" <<EOF
# Generated by setup-pm-second-brain.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
vault:
  root: "$VAULT_ROOT"
language: "$OUT_LANG"
llm:
  provider: "anthropic"
  primary_model: "claude-sonnet-4-6"
  cheap_model: "claude-haiku-4-5"
  prompt_caching: true
evolution:
  safety_gate: true
  auto_apply_trivial: true
  max_patches_per_week: 3
  evolve_after_tool_calls: 5
  pattern_threshold: 0.7
cron:
  daily_brief: "$CRON_TIME"
EOF
ok "wrote $CONFIG_PATH"

# --- 6. Initialize vault layout --------------------------------------------
info "Initializing vault layout…"
( cd "$HERE" && uv run --quiet python -c "
from pm_second_brain.config import load_config
from pm_second_brain.vault import init_vault
init_vault(load_config('$CONFIG_PATH'))
" ) || { fail "vault init failed"; exit 1; }
ok "vault layout ready at $VAULT_ROOT"

# --- 7. Initialize sqlite-fts schema ---------------------------------------
info "Initializing sqlite-fts session store…"
( cd "$HERE" && uv run --quiet python -c "
from pathlib import Path
from pm_second_brain.mcp_servers.sqlite_fts import FtsStore
db = Path('$VAULT_ROOT') / '_brain' / 'sessions.db'
db.parent.mkdir(parents=True, exist_ok=True)
FtsStore(db).init_schema()
" ) || { fail "sqlite-fts init failed"; exit 1; }
ok "sessions.db ready"

# --- 8. Symlink skills into runtimes ---------------------------------------
info "Linking skill namespaces into OpenCode and Claude Code…"
link_skills "$HERE" "$HOME/.opencode/skills"
ok "skills linked → $HOME/.opencode/skills"
link_skills "$HERE" "$HOME/.claude/skills"
ok "skills linked → $HOME/.claude/skills"

# --- 9. MCP configs --------------------------------------------------------
info "Rendering MCP configs…"
mkdir -p "$HOME/.opencode" "$HOME/.claude"
sed "s|{{VAULT_ROOT}}|$VAULT_ROOT|g;s|{{REPO_ROOT}}|$HERE|g" \
    "$HERE/mcp-configs/opencode.json" > "$HOME/.opencode/mcp.json"
sed "s|{{VAULT_ROOT}}|$VAULT_ROOT|g;s|{{REPO_ROOT}}|$HERE|g" \
    "$HERE/mcp-configs/claude-code.json" > "$HOME/.claude/mcp.json"
ok "MCP configs written"

# --- 10. Optional launchd schedule (macOS) ---------------------------------
if [[ "$OSTYPE" == "darwin"* ]]; then
  say ""
  if ask_yn "Install macOS launchd schedule for daily brief now?" y; then
    OPENCODE_BIN="$(command -v opencode || true)"
    if [[ -z "$OPENCODE_BIN" ]]; then
      warn "opencode binary not found on PATH — skipping launchd"
    else
      PLIST_PATH="$HOME/Library/LaunchAgents/com.pm-second-brain.daily-brief.plist"
      LOG_PATH="$HOME/Library/Logs/pm-second-brain-daily-brief.log"
      mkdir -p "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"
      ( cd "$HERE" && uv run --quiet python -c "
from pm_second_brain.cron import render_launchd_plist
print(render_launchd_plist(
  'com.pm-second-brain.daily-brief',
  '$OPENCODE_BIN',
  ['run', '--skill', 'pm-workflow.pm-daily-brief', '--headless'],
  '$CRON_TIME',
  '$LOG_PATH',
))" > "$PLIST_PATH" ) || { fail "plist render failed"; exit 1; }
      launchctl unload "$PLIST_PATH" 2>/dev/null || true
      launchctl load "$PLIST_PATH"
      ok "launchd job loaded → $PLIST_PATH"
    fi
  else
    info "Skipping launchd. Re-run later or use systemd template on Linux."
  fi
fi

say ""
ok "Setup complete."
say ""
say "Next steps:"
say "  - Open Obsidian, point it at: $VAULT_ROOT"
say "  - In OpenCode try:   opencode run --skill pm-workflow.pm-daily-brief"
say "  - In Claude Code:    /pm-workflow.pm-daily-brief"
